version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8041:80"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8042:8080"
    environment:
      MONGOSTRING: mongodb://database:27017
    depends_on:
      - database
      - emotion-api
    volumes:
      - backend_uploads:/app/uploads

  emotion-api:
    build:
      context: .
      dockerfile: Dockerfile.emotion
    ports:
      - "8043:5000"
    volumes:
      - emotion_snapshots:/app/snapshots

  database:
    image: mongo:latest

volumes:
  backend_uploads:
  emotion_snapshots:
  mongo_data:
